

#  DeaneP2
#  Programmer: Kyrsti Deane
#  Email: 'kdeane1@cnm.edu'
#  Purpose: Provide data for state entered by user


import random

capital_dict = {'Alabama' : 'Montgomery',
'Alaska' : 'Juneau',
'Arizona' : 'Phoenix',
'Arkansas' : 'Little Rock',
'California' : 'Sacramento',
'Colorado' : 'Denver',
'Connecticut' : 'Hartford',
'Delaware' : 'Dover',
'Florida' : 'Tallahassee',
'Georgia' : 'Atlanta',
'Hawaii' : 'Honolulu',
'Idaho' : 'Boise',
'Illinois' : 'Springfield',
'Indiana' : 'Indianapolis',
'Iowa' : 'Des Moines',
'Kansas' : 'Topeka',
'Kentucky' : 'Frankfort',
'Louisiana' : 'Baton Rouge',
'Maine' : 'Augusta',
'Maryland' : 'Annapolis',
'Massachusetts' : 'Boston',
'Michigan' : 'Lansing',
'Minnesota' : 'St. Paul',
'Mississippi' : 'Jackson',
'Missouri' : 'Jefferson City',
'Montana' : 'Helena',
'Nebraska' : 'Lincoln',
'Nevada' : 'Carson City',
'New Hampshire' : 'Concord',
'New Jersey' : 'Trenton',
'New Mexico' : 'Santa Fe',
'New York' : 'Albany',
'North Carolina' : 'Raleigh',
'North Dakota' : 'Bismarck',
'Ohio' : 'Columbus',
'Oklahoma' : 'Oklahoma City',
'Oregon' : 'Salem',
'Pennsylvania' : 'Harrisburg',
'Rhode Island' : 'Providence',
'South Carolina' : 'Columbia',
'South Dakota' : 'Pierre',
'Tennessee' : 'Nashville',
'Texas' : 'Austin',
'Utah' : 'Salt Lake City',
'Vermont' : 'Montpelier',
'Virginia' : 'Richmond',
'Washington' : 'Olympia',
'West Virginia' : 'Charleston',
'Wisconsin' : 'Madison',
'Wyoming' : 'Cheyenne',}

districts_dict = {'Alabama' : '7',
'Alaska' : '1',
'Arizona' : '8',
'Arkansas' : '4',
'California' : '53',
'Colorado' : '7',
'Connecticut' : '5',
'Delaware' : '1',
'Florida' : '25',
'Georgia' : '13',
'Hawaii' : '2',
'Idaho' : '2',
'Illinois' : '19',
'Indiana' : '9',
'Iowa' : '5',
'Kansas' : '4',
'Kentucky' : '6',
'Louisiana' : '7',
'Maine' : '2',
'Maryland' : '8',
'Massachusetts' : '10',
'Michigan' : '15',
'Minnesota' : '8',
'Mississippi' : '4',
'Missouri' : '9',
'Montana' : '1',
'Nebraska' : '3',
'Nevada' : '3',
'New Hampshire' : '2',
'New Jersey' : '13',
'New Mexico' : '3',
'New York' : '29',
'North Carolina' : '13',
'North Dakota' : '1',
'Ohio' : '18',
'Oklahoma' : '5',
'Oregon' : '5',
'Pennsylvania' : '19',
'Rhode Island' : '2',
'South Carolina' : '6',
'South Dakota' : '1',
'Tennessee' : '9',
'Texas' : '32',
'Utah' : '3',
'Vermont' : '1',
'Virginia' : '11',
'Washington' : '9',
'West Virginia' : '3',
'Wisconsin' : '8',
'Wyoming' : '1',}

joined_dict = {'Alabama' : '22',
'Alaska' : '49',
'Arizona' : '48',
'Arkansas' : '25',
'California' : '31',
'Colorado' : '38',
'Connecticut' : '5',
'Delaware' : '1',
'Florida' : '27',
'Georgia' : '4',
'Hawaii' : '50',
'Idaho' : '43',
'Illinois' : '21',
'Indiana' : '19',
'Iowa' : '29',
'Kansas' : '34',
'Kentucky' : '15',
'Louisiana' : '18',
'Maine' : '23',
'Maryland' : '7',
'Massachusetts' : '6',
'Michigan' : '26',
'Minnesota' : '32',
'Mississippi' : '20',
'Missouri' : '24',
'Montana' : '41',
'Nebraska' : '37',
'Nevada' : '36',
'New Hampshire' : '9',
'New Jersey' : '3',
'New Mexico' : '47',
'New York' : '11',
'North Carolina' : '12',
'North Dakota' : '39',
'Ohio' : '17',
'Oklahoma' : '46',
'Oregon' : '33',
'Pennsylvania' : '2',
'Rhode Island' : '13',
'South Carolina' : '8',
'South Dakota' : '40',
'Tennessee' : '16',
'Texas' : '28',
'Utah' : '45',
'Vermont' : '14',
'Virginia' : '10',
'Washington' : '42',
'West Virginia' : '35',
'Wisconsin' : '30',
'Wyoming' : '44',}


states = ['Alabama',
'Alaska',
'Arizona',
'Arkansas',
'California',
'Colorado',
'Connecticut',
'Delaware',
'Florida',
'Georgia',
'Hawaii',
'Idaho',
'Illinois',
'Indiana',
'Iowa',
'Kansas',
'Kentucky',
'Louisiana',
'Maine',
'Maryland',
'Massachusetts',
'Michigan',
'Minnesota',
'Mississippi',
'Missouri',
'Montana',
'Nebraska',
'Nevada',
'New Hampshire',
'New Jersey',
'New Mexico',
'New York',
'North Carolina',
'North Dakota',
'Ohio',
'Oklahoma',
'Oregon',
'Pennsylvania',
'Rhode Island',
'South Carolina',
'South Dakota',
'Tennessee',
'Texas',
'Utah',
'Vermont',
'Virginia',
'Washington',
'West Virginia',
'Wisconsin',
'Wyoming',]



import random


user_input = input('Please enter the name of a state as a proper noun: ')
state = user_input
capital = capital_dict[state]
num_districts = districts_dict[state]
joined = joined_dict[state]


if user_input == state:
    print('The capital of ' + state + ' is ' + capital + '.')
    print('The state of ' + state + ' has ' + num_districts + ' congressional districts.')
    print(state + ' was state number ' + joined + ' to join the union.')
else:
    print('The state name entered was not valid.')

